 eureka:
          client:
            register-with-eureka: true
            fetch-register: true
            service-url:
              defaultzone: http://localhost:8761/eureka/
              instance:
                hostname: localhost

microservice:
  STUDENT-WRAPPER:
  endpoints:
  endpoint:
  uri: http://STUDENT-WRAPPER/do-student
